version: '3.8'

services:
  task-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: 'mongodb://mongo:27017/taskdb'  # Connect to MongoDB service
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
